name: Run Jest Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm' # Cache npm dependencies
      - name: Install dependencies
        run: npm ci # Use npm ci for consistent installs
      - name: Verify Jest installation
        run: npx jest --version # Check Jest version with npx
      - name: Run Jest tests
        run: npx jest